on: 
   workflow_dispatch:
jobs:
  my_job: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - name: Build project with Maven
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn -B package --file pom.xml   
    - name: Build Container image
      env: 
         IMAGE_TAG : ${{ github.sha }}
      run: |
         cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
         docker build -t dumalbhaskar/myimages:${IMAGE_TAG} . 
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
         docker push dumalbhaskar/myimages:${IMAGE_TAG}
    - name: update manifest
      env: 
         BUILD_NIMBER:  ${{ github.sha }}
         GIT_REPO_NAME: "TestRepo"
         GIT_USER_NAME: "dumalbhaskar"
         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         IMAGE_TAG: ${{ github.sha }}
         IMAGE_NAME: "dumalbhaskar/myimages"
         
         
      run: |
            mkdir /tmp/temp_repo && cd /tmp/temp_repo
            git config --global user.email "dumal@gmail.com"
            git config --global user.name "Dumal Bhaskar"
            git clone https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git
            ls -l
            cd TestRepo
            sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
            git add . 
            git commit -m "update"
            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                  
