on: 
   workflow_dispatch:
jobs:
  my_job: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - name: Build project with Maven
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn -B package --file pom.xml   
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
         image: dumalbhaskar/myimages
         tags: v1, latest
         registry: docker.io
         dockerfile: java-maven-sonar-argocd-helm-k8s/spring-boot-app/Dockerfile
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
