on: 
   workflow_dispatch:
jobs:
  my_job: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - name: Build project with Maven
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn -B package --file pom.xml   
    - name: Build Container image
      env: 
         IMAGE_TAG : ${{ github.sha }}
      run: |
         cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
         docker build -t dumalbhaskar/myimages:${IMAGE_TAG} . 
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
         docker push dumalbhaskar/myimages:${IMAGE_TAG}
    - name: update manifest
      env: 
         BUILD_NIMBER:  ${{ github.sha }}
         GIT_REPO_NAME: "TestRepo"
         GIT_USER_NAME: "iam-veeramalla"
         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
                    git config user.email "abhi@gmail.com"
                    git config user.name "dumal bhaskar"
                    git clone "https://github.com/DumalBhaskar/TestRepo.git"
                    cd java-maven-sonar-argocd-helm-k8s
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
                    git add .
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
