on: 
   workflow_dispatch:
jobs:
  my_job: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - name: Build project with Maven
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn -B package --file pom.xml   
    - name: Build Container image
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t dumalbhaskar/myimages:latest . 
    - name: docker push 
      run: docker push dumalbhaskar/myimages
