on: 
   workflow_dispatch:
jobs:
  my_job: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - run: | 
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
         name: Package
         path: staging
